name: ${project.name}
description: Some EULA friendly perks.
author: Ben12345rocks
version: ${project.version}
main: com.Ben12345rocks.MCPerks.Main
softdepend: [VotingPlugin]
api-version: 1.13
commands:
  mcperks:
    description: MCPerks commands
    aliases: [mcp, perks]
  mcperksreload:
    description: MCPerks commands
  mcperkshelp:
    description: MCPerks commands